# Generated by Django 5.2.17 on 2026-09-10 21:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='facultyprofile',
            table='faculty_profiles',
        ),
        migrations.AlterModelTable(
            name='studentprofile',
            table='student_profiles',
        ),
        migrations.AlterModelTable(
            name='user',
            table='users',
        ),
    ]
