# Generated by Django 5.2.17 on 2026-09-10 21:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0005_queue_missing_lessons'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='conversation',
            new_name='tutor_conve_student_32f8a4_idx',
            old_name='tutor_conve_student_0ce6ce_idx',
        ),
        migrations.AlterModelTable(
            name='conversation',
            table='tutor_conversations',
        ),
        migrations.AlterModelTable(
            name='message',
            table='tutor_messages',
        ),
        migrations.AlterModelTable(
            name='modulelesson',
            table='module_lessons',
        ),
    ]
