#!/usr/bin/env python3
"""LocalMind standalone launcher: one command, one process, works offline.

    python run_localmind.py            # serve on http://<this-machine>:8000 and open a browser
    python run_localmind.py --port 8080 --no-browser

What it does, in order: writes a backend/.env with a generated secret if
there is none, applies migrations, creates the first admin if the database is
empty, verifies the embedded AI model (and loads it so the first request is
fast), then serves the API, the media folder and the built web client from a
single port with waitress. Students, faculty and admins on the same network
open http://<host-ip>:8000 in any browser; nothing is installed on their
machines and nothing on this one needs the internet.

Prerequisites on the host (done once by start.bat / start.sh, or by hand):
  * the Python virtual environment in backend/.venv with requirements installed
  * frontend/dist  (npm run export:web)            -- the web client
  * backend/models/<model>.gguf  (manage.py fetch_model)  -- the AI model
  * backend/models/docling/      (manage.py fetch_model --docling)  -- PDF parsing
"""
import argparse
import os
import secrets
import socket
import sys
import threading
import webbrowser
from pathlib import Path

ROOT = Path(__file__).resolve().parent
BACKEND = ROOT / "backend"


def lan_ip() -> str:
    s = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)
    try:
        s.connect(("10.255.255.255", 1))
        return s.getsockname()[0]
    except OSError:
        return "127.0.0.1"
    finally:
        s.close()


def ensure_env():
    env = BACKEND / ".env"
    if env.exists():
        return
    env.write_text(
        "# Generated by run_localmind.py. Every new account starts on INITIAL_USER_PASSWORD\n"
        "# and must change it at first login (INITIAL_PASSWORD_MODE=unique gives each account\n"
        "# its own one-time password instead). TRUSTED_PROXY_COUNT=0 because nothing sits in front.\n"
        f"DJANGO_SECRET_KEY={secrets.token_urlsafe(48)}\n"
        "DJANGO_DEBUG=false\n"
        "DJANGO_ALLOWED_HOSTS=*\n"
        "DATABASE_URL=sqlite:///db.sqlite3\n"
        "AI_PROVIDER=llamacpp\n"
        "SERVE_WEB=true\n"
        "SERVE_MEDIA=true\n"
        "INITIAL_PASSWORD_MODE=shared\n"
        "INITIAL_USER_PASSWORD=Welcome@LocalMind1\n"
        "TRUSTED_PROXY_COUNT=0\n",
        encoding="utf-8",
    )
    print(f"Wrote {env}")


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--host", default="0.0.0.0")
    ap.add_argument("--port", type=int, default=int(os.environ.get("PORT", "8000")))
    ap.add_argument("--threads", type=int, default=8)
    ap.add_argument("--no-browser", action="store_true")
    ap.add_argument("--admin-email", default=os.environ.get("BOOTSTRAP_ADMIN_EMAIL", "admin@localmind.local"))
    ap.add_argument("--skip-ai-check", action="store_true", help="Start even if the model is missing (AI features use fallbacks).")
    args = ap.parse_args()

    os.chdir(BACKEND)
    sys.path.insert(0, str(BACKEND))
    ensure_env()
    os.environ.setdefault("DJANGO_SETTINGS_MODULE", "config.settings")
    os.environ.setdefault("DJANGO_ALLOWED_HOSTS", "*")

    import django

    django.setup()
    from django.conf import settings
    from django.core.management import call_command

    call_command("migrate", interactive=False, verbosity=0)
    try:
        call_command("collectstatic", interactive=False, verbosity=0)
    except Exception as exc:  # static files are only the DRF/admin assets; not fatal
        print(f"collectstatic skipped: {exc}")

    from django.contrib.auth import get_user_model

    User = get_user_model()
    if not User.objects.exists():
        call_command("bootstrap_admin", email=args.admin_email)
        if settings.LOCALMIND.get("INITIAL_PASSWORD_MODE") == "shared":
            print(f"Created first admin {args.admin_email} with the initial password from backend/.env")
        else:
            print(f"Created first admin {args.admin_email}. Sign in with the one-time password printed above; "
                  "it must be changed at first login.")

    if not settings.SERVE_WEB:
        print("WARNING: frontend/dist is missing; the browser UI will not be served. Run `npm run export:web` in frontend/.")

    if settings.AI["ENABLED"] and not args.skip_ai_check:
        try:
            call_command("check_ai")
        except Exception as exc:
            print(f"AI not ready: {exc}\nStarting anyway; quizzes, assignments and the tutor will use their deterministic fallbacks "
                  "until the model is available (python manage.py fetch_model).")

    from jobs.services import start_local_worker
    start_local_worker()

    from waitress import serve

    from config.wsgi import application

    url = f"http://{lan_ip() if args.host == '0.0.0.0' else args.host}:{args.port}"
    print(f"\nLocalMind is running at {url}  (also http://127.0.0.1:{args.port})\nPress Ctrl+C to stop.\n")
    if not args.no_browser:
        threading.Timer(1.5, lambda: webbrowser.open(f"http://127.0.0.1:{args.port}")).start()
    serve(application, host=args.host, port=args.port, threads=args.threads, channel_timeout=600)


if __name__ == "__main__":
    main()
