const test=require('node:test'), assert=require('node:assert/strict'), crypto=require('node:crypto');
const core=require('../.test-build/core.js');
const fixture=require('./signed-fixture.json');
const fresh=()=>JSON.parse(fixture.envelope.payload), id=n=>`00000000-0000-0000-0000-${String(n).padStart(12,'0')}`;
const verify=(message,sig,key)=>crypto.verify(null,message,crypto.createPublicKey({key:Buffer.concat([Buffer.from('302a300506032b6570032100','hex'),Buffer.from(key)]),format:'der',type:'spki'}),sig);
const session=(model={complete:async()=>{throw new Error('Model unavailable')}})=>new core.StudySession(fresh(),model);
const raw=()=>JSON.stringify(fixture.envelope);
test('real Python signature verifies in JavaScript',()=>assert.equal(core.verifyPackage(raw(),fixture.trusted,verify).content.version,1));
test('tampered signed bytes are rejected',()=>assert.throws(()=>core.verifyPackage(JSON.stringify({...fixture.envelope,payload:fixture.envelope.payload+' '}),fixture.trusted,verify),/signature/));
test('embedded untrusted publisher key is not accepted',()=>assert.throws(()=>core.verifyPackage(raw(),{},verify),/trusted/));
test('extra envelope data is rejected',()=>assert.throws(()=>core.verifyPackage(JSON.stringify({...fixture.envelope,public_key:'bad'}),fixture.trusted,verify)));
test('unknown package fields are rejected',()=>{const p=fresh();p.student_id='bad';assert.throws(()=>core.validatePackage(p));});
test('duplicate block identity rejected',()=>{const p=fresh();p.blocks.push(p.blocks[0]);assert.throws(()=>core.validatePackage(p));});
test('stale source revision rejected',()=>{const p=fresh();p.questions[0].references[0].revision=2;assert.throws(()=>core.validatePackage(p),/stale/);});
test('missing module membership rejected',()=>{const p=fresh();p.modules[0].blocks.pop();assert.throws(()=>core.validatePackage(p));});
test('empty source block rejected',()=>{const p=fresh();p.blocks[0].text='';assert.throws(()=>core.validatePackage(p));});
test('oversized source block rejected',()=>{const p=fresh();p.blocks[0].text='x'.repeat(3501);assert.throws(()=>core.validatePackage(p));});
test('unsupported question quote rejected',()=>{const p=fresh();p.questions[0].body.quote='not in the book';assert.throws(()=>core.validatePackage(p));});
test('unrecognized teaching move rejected',()=>{const p=fresh();p.policy.question[0]='invent_question';assert.throws(()=>core.validatePackage(p));});
test('all five authored moves become available',()=>assert.deepEqual(core.availableMoves(fresh().blocks[0]),[...core.MOVES]));
test('missing teaching aids leave only re-teach',()=>assert.deepEqual(core.availableMoves(fresh().blocks[1]),['reteach']));
test('prerequisite cycles rejected',()=>{const p=fresh();p.blocks[2].aids.prerequisites=[{id:id(3),revision:1}];assert.throws(()=>core.validatePackage(p),/Cyclic/);});
test('diagnostic must reference its block',()=>{const p=fresh();p.blocks[1].aids.diagnostics=[id(6)];assert.throws(()=>core.validatePackage(p));});
test('session is pinned to its own snapshot',()=>{const p=fresh(),s=new core.StudySession(p,{});p.version=2;p.blocks[0].text='changed';assert.equal(s.content.version,1);assert.notEqual(s.block(id(3)).text,'changed');});
test('Q&A resolves a stored block',async()=>{let req;const s=session({complete:async r=>(req=r,{supported:true,explanation:'Each row has a unique key.',quote:'uniquely identifies each row'})});const a=await s.explain(id(3),'Explain this');assert.equal(a.supported,true);assert.match(req.messages[1].content,/STORED REFERENCE/);assert.equal(req.maxTokens,420);});
test('unknown source id never calls the model',async()=>{let calls=0;const s=session({complete:async()=>{calls++}});await assert.rejects(s.explain(id(99),'Hi'));assert.equal(calls,0);});
test('an unsupported answer is replaced with clear guidance',async()=>{const s=session({complete:async()=>({supported:false,explanation:'An invented answer',quote:''})});assert.match((await s.explain(id(3),'Not here')).explanation,/not covered/);});
test('fabricated model quote is refused',async()=>{const s=session({complete:async()=>({supported:true,explanation:'Incorrect',quote:'not in source'})});await assert.rejects(s.explain(id(3),'Explain'),/unsupported/);});
for(const move of core.MOVES)test(`available move ${move} uses stored material`,async()=>{let calls=0;const s=session({complete:async()=>++calls===1?{move}:{supported:true,explanation:'A key identifies a row.',quote:'identifies each row'}});const h=await s.help(id(3),'definition_miss',{...core.INITIAL_LEARNER});assert.equal(h.move,move);});
test('unavailable move cannot be selected by model',async()=>{const s=session({complete:async()=>({move:'simplify'})});await assert.rejects(s.help(id(4),'question',core.INITIAL_LEARNER));});
test('MCQ practice runs without a model and returns no grade',()=>{const a=session().checkMCQ(id(6),0);assert.equal(a.understood,true);assert.equal('score'in a,false);assert.equal('grade'in a,false);assert.equal(session().checkMCQ(id(6),1).understood,false);});
test('out-of-range answer refused',()=>assert.throws(()=>session().checkMCQ(id(6),4)));
test('short practice validates rubric coverage without a score',async()=>{const s=session({complete:async()=>({covered:[0],missing:[1],feedback:'Explain uniqueness too.',quote:'uniquely identifies each row'})});const a=await s.checkShort(id(7),'Identifies a row');assert.equal(a.understood,false);assert.deepEqual(a.missing,['Is unique']);assert.equal('score'in a,false);});
test('duplicated rubric index is not a successful answer',async()=>{const s=session({complete:async()=>({covered:[0,0],missing:[],feedback:'Done',quote:'identifies each row'})});await assert.rejects(s.checkShort(id(7),'answer'));});
test('observation contains only fixed research fields',()=>{const e=core.observation(session(),id(30),id(3),'question','reteach','retry_needed',id(6));assert.deepEqual(Object.keys(e).sort(),['id','package_id','version','block_id','block_revision','question_id','state','move','outcome'].sort());});
test('unrelated practice question cannot be attached to an event',()=>assert.throws(()=>core.observation(session(),id(30),id(4),'question','reteach','retry_needed',id(6))));
test('arbitrary observation strings cannot leak raw questions',()=>assert.throws(()=>core.observation(session(),id(30),id(3),'my raw question','reteach','retry_needed')));
