const test=require('node:test'),assert=require('node:assert/strict'),path=require('node:path');
const {DraftPersistence,carryEditableFields}=require(path.join(process.env.LOCALMIND_DRAFT_BUILD,'draftPersistence.js'));
let seq=0;const tick=()=>new Promise(setImmediate);
function deferred(){let resolve,reject;const promise=new Promise((a,b)=>{resolve=a;reject=b});return{promise,resolve,reject};}
function storage(initial=null){let value=initial;return{getItem:async()=>value,setItem:async(k,v)=>{value=v},removeItem:async()=>{value=null},value:()=>value};}
function make(s,initial={}){return new DraftPersistence(s,`test-${seq++}`,initial);}
test('saved quiz answers are restored',async()=>{const d=make(storage('{"q1":"A","q2":"B"}'));assert.deepEqual(await d.load(),{q1:'A',q2:'B'});assert.equal(d.dirty,false);});
test('early changes merge by question instead of dropping saved answers',async()=>{const wait=deferred(),s=storage();s.getItem=()=>wait.promise;const d=make(s);const load=d.load();d.update({q1:'C'});wait.resolve('{"q1":"A","q2":"B"}');assert.deepEqual(await load,{q1:'C',q2:'B'});assert.equal(await d.flush(),true);assert.deepEqual(JSON.parse(s.value()),{q1:'C',q2:'B'});});
test('failed persistence rejects rather than allowing departure',async()=>{const s=storage(),d=make(s);await d.load();d.update({q1:'A'});s.setItem=async()=>{throw new Error('disk full')};await assert.rejects(d.flush(),/disk full/);assert.equal(d.dirty,true);});
test('successful retry persists the unsaved draft',async()=>{const s=storage(),write=s.setItem,d=make(s);await d.load();d.update({q1:'A'});s.setItem=async()=>{throw new Error('full')};await assert.rejects(d.flush());s.setItem=write;assert.equal(await d.flush(),true);});
test('edits made during a write keep that save dirty',async()=>{const s=storage(),gate=deferred(),write=s.setItem;let calls=0;s.setItem=async(k,v)=>{if(++calls===1)await gate.promise;await write(k,v)};const d=make(s);await d.load();d.update({q1:'A'});const first=d.flush();await tick();d.update({q1:'B'});const second=d.flush();gate.resolve();assert.equal(await first,false);assert.equal(await second,true);assert.equal(JSON.parse(s.value()).q1,'B');});
test('discard removes persisted draft',async()=>{const s=storage('{"q1":"A"}'),d=make(s);await d.load();await d.discard();assert.equal(s.value(),null);assert.equal(await d.flush(),false);});
test('discard fences an earlier in-flight write',async()=>{const s=storage(),gate=deferred(),write=s.setItem;s.setItem=async(k,v)=>{await gate.promise;await write(k,v)};const d=make(s);await d.load();d.update({q1:'A'});const saving=d.flush();await tick();const removing=d.discard();gate.resolve();assert.equal(await saving,false);await removing;assert.equal(s.value(),null);});
test('unreadable saved data is not overwritten',async()=>{const s=storage('not-json'),d=make(s);await assert.rejects(d.load());await assert.rejects(d.flush());assert.equal(s.value(),'not-json');});
test('new server version keeps server metadata and only newer editable fields',()=>{const server={id:'new',version:2,status:'draft',attempt_count:0,title:'submitted',questions:['A']},sent={...server,id:'old',version:1,status:'published',attempt_count:4,title:'submitted'},current={...sent,title:'new typing'};const carried=carryEditableFields(server,sent,current,['title','questions']);assert.equal(carried.id,'new');assert.equal(carried.status,'draft');assert.equal(carried.attempt_count,0);assert.equal(carried.version,2);assert.equal(carried.title,'new typing');});
