# Generated by Django 5.2.17 on 2026-09-02 10:49

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0002_initial'),
        ('learning', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Assessment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kind', models.CharField(choices=[('module', 'Module quiz'), ('chapter', 'Chapter quiz')], max_length=10)),
                ('title', models.CharField(max_length=300)),
                ('instructions', models.TextField(blank=True)),
                ('questions', models.JSONField(default=list)),
                ('generator', models.CharField(choices=[('ai', 'AI generated'), ('fallback', 'Fallback generator'), ('manual', 'Manually authored')], default='manual', max_length=10)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('closed', 'Closed'), ('superseded', 'Superseded by a newer version')], db_index=True, default='draft', max_length=12)),
                ('pass_percentage', models.PositiveSmallIntegerField(default=65)),
                ('max_attempts', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('time_limit_minutes', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('available_from', models.DateTimeField(blank=True, null=True)),
                ('due_at', models.DateTimeField(blank=True, null=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('content_version_at_creation', models.PositiveIntegerField(default=1)),
                ('chapter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='assessments', to='learning.chapter')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('module', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='assessments', to='learning.module')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assessments', to='academics.subject')),
                ('supersedes', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='superseded_by', to='assessments.assessment')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AssessmentAttempt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('attempt_number', models.PositiveSmallIntegerField()),
                ('status', models.CharField(choices=[('in_progress', 'In progress'), ('submitted', 'Submitted'), ('pending_evaluation', 'Pending subjective evaluation'), ('evaluated', 'Evaluated')], db_index=True, default='in_progress', max_length=20)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('time_taken_seconds', models.PositiveIntegerField(blank=True, null=True)),
                ('submitted_answers', models.JSONField(default=dict)),
                ('score', models.FloatField(blank=True, null=True)),
                ('total_questions', models.PositiveSmallIntegerField(default=0)),
                ('percentage', models.FloatField(blank=True, null=True)),
                ('passed', models.BooleanField(blank=True, null=True)),
                ('detailed_results', models.JSONField(default=list)),
                ('evaluation_notes', models.JSONField(blank=True, default=dict)),
                ('evaluated_at', models.DateTimeField(blank=True, null=True)),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attempts', to='assessments.assessment')),
                ('evaluated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessment_attempts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.AddIndex(
            model_name='assessment',
            index=models.Index(fields=['subject', 'status'], name='assessments_subject_fb0f9a_idx'),
        ),
        migrations.AddIndex(
            model_name='assessment',
            index=models.Index(fields=['module', 'status'], name='assessments_module__45aa3f_idx'),
        ),
        migrations.AddIndex(
            model_name='assessmentattempt',
            index=models.Index(fields=['student', 'status'], name='assessments_student_30c9da_idx'),
        ),
        migrations.AddConstraint(
            model_name='assessmentattempt',
            constraint=models.UniqueConstraint(fields=('assessment', 'student', 'attempt_number'), name='uniq_attempt_number'),
        ),
    ]
