# Generated by Django 5.2.17 on 2026-09-10 11:28

from django.db import migrations, models
from django.db.models import F


def mark_existing_outcomes_recorded(apps, schema_editor):
    """Before this migration every evaluated attempt wrote ModuleProgress at
    grading time. Mark those as recorded so a later re-evaluation or release
    does not count them a second time."""
    Attempt = apps.get_model("assessments", "AssessmentAttempt")
    Attempt.objects.filter(status="evaluated", outcome_recorded_at__isnull=True).update(
        outcome_recorded_at=F("updated_at"))


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0002_assessment_results_release_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessmentattempt',
            name='outcome_recorded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.RunPython(mark_existing_outcomes_recorded, migrations.RunPython.noop),
    ]
