# Generated by Django 5.2.17 on 2026-09-10 17:12

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0003_attempt_outcome_recorded_at'),
        ('learning', '0002_remove_modules_without_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessment',
            name='auto_generated',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.CreateModel(
            name='AutoQuizJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('pending', 'Waiting to be generated'), ('generating', 'Being generated'), ('ready', 'Ready'), ('failed', 'Generation failed'), ('dismissed', 'Deleted by faculty; not generated again')], db_index=True, default='pending', max_length=12)),
                ('source_hash', models.CharField(blank=True, max_length=64)),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('last_error', models.CharField(blank=True, max_length=300)),
                ('note', models.CharField(blank=True, max_length=300)),
                ('requested_at', models.DateTimeField(blank=True, null=True)),
                ('claimed_at', models.DateTimeField(blank=True, null=True)),
                ('generated_at', models.DateTimeField(blank=True, null=True)),
                ('next_attempt_at', models.DateTimeField(blank=True, null=True)),
                ('version', models.PositiveIntegerField(default=0)),
                ('assessment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='assessments.assessment')),
                ('module', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='auto_quiz_job', to='learning.module')),
            ],
            options={
                'indexes': [models.Index(fields=['status', 'next_attempt_at'], name='assess_autoquiz_queue_idx')],
            },
        ),
    ]
