# Generated by Django 5.2.17 on 2026-09-10 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0004_auto_quizzes'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessment',
            name='checked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='assessment',
            name='held_for_review',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='assessment',
            name='hold_reason',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
