# Generated by Django 5.2.17 on 2026-09-10 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0006_hold_flagged_auto_quizzes'),
        ('learning', '0003_short_table_names'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='assessment',
            new_name='quizzes_subject_1e21e6_idx',
            old_name='assessments_subject_fb0f9a_idx',
        ),
        migrations.RenameIndex(
            model_name='assessment',
            new_name='quizzes_module__8c601d_idx',
            old_name='assessments_module__45aa3f_idx',
        ),
        migrations.RenameIndex(
            model_name='assessmentattempt',
            new_name='quiz_attemp_student_be0fc9_idx',
            old_name='assessments_student_30c9da_idx',
        ),
        migrations.AlterField(
            model_name='assessment',
            name='source_modules',
            field=models.ManyToManyField(blank=True, db_table='quiz_modules', related_name='sourced_assessments', to='learning.module'),
        ),
        migrations.AlterModelTable(
            name='assessment',
            table='quizzes',
        ),
        migrations.AlterModelTable(
            name='assessmentattempt',
            table='quiz_attempts',
        ),
        migrations.AlterModelTable(
            name='autoquizjob',
            table='auto_quiz_jobs',
        ),
    ]
