# Generated by Django 5.2.17 on 2026-09-10 21:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='enrollment',
            table='student_enrollments',
        ),
        migrations.AlterModelTable(
            name='facultysubject',
            table='faculty_subjects',
        ),
        migrations.AlterModelTable(
            name='subject',
            table='subjects',
        ),
    ]
