# Generated by Django 5.2.17 on 2026-09-10 21:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0002_activityevent'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='activityevent',
            new_name='time_spent_user_id_697496_idx',
            old_name='activity_ac_user_id_2990cb_idx',
        ),
        migrations.RenameIndex(
            model_name='applicationsession',
            new_name='login_sessi_user_id_c4b3a9_idx',
            old_name='activity_ap_user_id_8ae018_idx',
        ),
        migrations.AlterModelTable(
            name='activityevent',
            table='time_spent',
        ),
        migrations.AlterModelTable(
            name='applicationsession',
            table='login_sessions',
        ),
    ]
