# Generated by Django 5.2.17 on 2026-09-10 21:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0002_remove_modules_without_text'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='moduleprogress',
            new_name='module_prog_student_51ab98_idx',
            old_name='learning_mo_student_57fbcf_idx',
        ),
        migrations.AlterModelTable(
            name='chapter',
            table='chapters',
        ),
        migrations.AlterModelTable(
            name='module',
            table='modules',
        ),
        migrations.AlterModelTable(
            name='moduleprogress',
            table='module_progress',
        ),
    ]
