# Generated by Django 5.2.17 on 2026-09-14 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0004_coursesyncreceipt'),
    ]

    operations = [
        migrations.AddField(
            model_name='moduleprogress',
            name='lesson_viewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
