# Generated by Django 5.2.17 on 2026-09-30 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0006_complete_finished_modules'),
    ]

    operations = [
        migrations.AddField(
            model_name='moduleprogress',
            name='read_source_hash',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='moduleprogress',
            name='reopened_reason',
            field=models.CharField(blank=True, default='', max_length=16),
        ),
    ]
