# Generated by Django 5.2.17 on 2026-09-09 10:35

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0002_initial'),
        ('assessments', '0002_assessment_results_release_and_more'),
        ('learning', '0001_initial'),
        ('tutor', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Evaluation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('interaction_kind', models.CharField(choices=[('tutor_answer', 'Tutor answer'), ('quiz', 'AI-generated quiz')], db_index=True, max_length=20)),
                ('interaction_id', models.UUIDField(db_index=True)),
                ('app_model_name', models.CharField(blank=True, db_index=True, max_length=100)),
                ('prompt_excerpt', models.TextField(blank=True)),
                ('response_excerpt', models.TextField(blank=True)),
                ('evidence_json', models.JSONField(blank=True, default=list)),
                ('validators_json', models.JSONField(blank=True, default=list)),
                ('judge_invoked', models.BooleanField(default=False)),
                ('judge_reason', models.CharField(blank=True, max_length=60)),
                ('judge_json', models.JSONField(blank=True, default=dict)),
                ('judge_model', models.CharField(blank=True, max_length=120)),
                ('judge_latency_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('judge_error', models.CharField(blank=True, max_length=300)),
                ('verdict', models.CharField(choices=[('pass', 'No issue found'), ('issue', 'Issue found'), ('abstain', 'Insufficient evidence')], db_index=True, default='pass', max_length=10)),
                ('issue_type', models.CharField(choices=[('none', 'None'), ('hallucination', 'Hallucination'), ('factual_error', 'Factual error'), ('unsupported_claim', 'Unsupported claim'), ('instruction_violation', 'Instruction violation'), ('quiz_error', 'Quiz error'), ('safety', 'Safety'), ('irrelevant', 'Irrelevant response'), ('other', 'Other')], db_index=True, default='none', max_length=30)),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], db_index=True, default='low', max_length=10)),
                ('confidence', models.FloatField(default=0.0)),
                ('reason', models.TextField(blank=True)),
                ('recommended_action', models.CharField(choices=[('review', 'Review'), ('correct_content', 'Correct content'), ('retrain/evaluate', 'Retrain or re-evaluate model'), ('no_action', 'No action')], default='no_action', max_length=20)),
                ('evaluator_version', models.CharField(db_index=True, max_length=20)),
                ('stage', models.CharField(choices=[('pending', 'Queued'), ('done', 'Evaluated'), ('failed', 'Evaluator failed')], db_index=True, default='done', max_length=10)),
                ('error', models.CharField(blank=True, max_length=300)),
                ('duration_ms', models.PositiveIntegerField(default=0)),
                ('assessment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='monitor_evaluations', to='assessments.assessment')),
                ('message', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='monitor_evaluations', to='tutor.message')),
                ('module', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='monitor_evaluations', to='learning.module')),
                ('subject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='monitor_evaluations', to='academics.subject')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='monitor_evaluations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('issue_type', models.CharField(choices=[('none', 'None'), ('hallucination', 'Hallucination'), ('factual_error', 'Factual error'), ('unsupported_claim', 'Unsupported claim'), ('instruction_violation', 'Instruction violation'), ('quiz_error', 'Quiz error'), ('safety', 'Safety'), ('irrelevant', 'Irrelevant response'), ('other', 'Other')], db_index=True, max_length=30)),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], db_index=True, max_length=10)),
                ('status', models.CharField(choices=[('open', 'Open'), ('confirmed', 'Confirmed'), ('false_positive', 'False positive'), ('needs_investigation', 'Needs investigation'), ('escalated', 'Escalated'), ('closed', 'Closed')], db_index=True, default='open', max_length=25)),
                ('reviewer_note', models.TextField(blank=True)),
                ('recurrence', models.PositiveIntegerField(default=0)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_monitor_incidents', to=settings.AUTH_USER_MODEL)),
                ('evaluation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='incident', to='ai_monitor.evaluation')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('subject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='monitor_incidents', to='academics.subject')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='monitor_incidents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('label', models.CharField(choices=[('correct', 'Verdict was correct'), ('false_positive', 'False positive'), ('needs_investigation', 'Needs investigation')], db_index=True, max_length=25)),
                ('note', models.TextField(blank=True)),
                ('evaluation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback', to='ai_monitor.evaluation')),
                ('reviewer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='monitor_feedback', to=settings.AUTH_USER_MODEL)),
                ('incident', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feedback', to='ai_monitor.incident')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Policy',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('issue_type', models.CharField(choices=[('none', 'None'), ('hallucination', 'Hallucination'), ('factual_error', 'Factual error'), ('unsupported_claim', 'Unsupported claim'), ('instruction_violation', 'Instruction violation'), ('quiz_error', 'Quiz error'), ('safety', 'Safety'), ('irrelevant', 'Irrelevant response'), ('other', 'Other')], max_length=30, unique=True)),
                ('enabled', models.BooleanField(default=True)),
                ('min_confidence', models.FloatField(default=0.7)),
                ('min_severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=10)),
                ('description', models.CharField(blank=True, max_length=300)),
                ('version', models.PositiveIntegerField(default=1)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'policies',
                'ordering': ['issue_type'],
            },
        ),
        migrations.AddIndex(
            model_name='evaluation',
            index=models.Index(fields=['verdict', 'severity'], name='ai_monitor__verdict_09f6aa_idx'),
        ),
        migrations.AddIndex(
            model_name='evaluation',
            index=models.Index(fields=['subject', 'created_at'], name='ai_monitor__subject_1768ec_idx'),
        ),
        migrations.AddIndex(
            model_name='evaluation',
            index=models.Index(fields=['app_model_name', 'created_at'], name='ai_monitor__app_mod_9b7b6e_idx'),
        ),
        migrations.AddConstraint(
            model_name='evaluation',
            constraint=models.UniqueConstraint(fields=('interaction_kind', 'interaction_id', 'evaluator_version'), name='uniq_evaluation_per_interaction_version'),
        ),
        migrations.AddIndex(
            model_name='incident',
            index=models.Index(fields=['status', 'severity'], name='ai_monitor__status_ff281d_idx'),
        ),
        migrations.AddIndex(
            model_name='incident',
            index=models.Index(fields=['subject', 'status'], name='ai_monitor__subject_99ceed_idx'),
        ),
    ]
