# Generated by Django 5.2.17 on 2026-09-10 21:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ai_monitor', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='evaluation',
            new_name='ai_checks_verdict_6ec078_idx',
            old_name='ai_monitor__verdict_09f6aa_idx',
        ),
        migrations.RenameIndex(
            model_name='evaluation',
            new_name='ai_checks_subject_715aa7_idx',
            old_name='ai_monitor__subject_1768ec_idx',
        ),
        migrations.RenameIndex(
            model_name='evaluation',
            new_name='ai_checks_app_mod_2d1b7e_idx',
            old_name='ai_monitor__app_mod_9b7b6e_idx',
        ),
        migrations.RenameIndex(
            model_name='incident',
            new_name='ai_incident_status_f2f981_idx',
            old_name='ai_monitor__status_ff281d_idx',
        ),
        migrations.RenameIndex(
            model_name='incident',
            new_name='ai_incident_subject_01a706_idx',
            old_name='ai_monitor__subject_99ceed_idx',
        ),
        migrations.AlterModelTable(
            name='evaluation',
            table='ai_checks',
        ),
        migrations.AlterModelTable(
            name='feedback',
            table='ai_check_feedback',
        ),
        migrations.AlterModelTable(
            name='incident',
            table='ai_incidents',
        ),
        migrations.AlterModelTable(
            name='policy',
            table='ai_incident_rules',
        ),
    ]
