# Generated by Django 5.2.17 on 2026-09-10 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0002_assignment_results_release_and_more'),
        ('learning', '0003_short_table_names'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='assignment',
            new_name='assignments_subject_bef218_idx',
            old_name='assignments_subject_8b6132_idx',
        ),
        migrations.AlterField(
            model_name='assignment',
            name='source_modules',
            field=models.ManyToManyField(blank=True, db_table='assignment_modules', related_name='sourced_assignments', to='learning.module'),
        ),
        migrations.AlterModelTable(
            name='assignment',
            table='assignments',
        ),
        migrations.AlterModelTable(
            name='assignmentsubmission',
            table='assignment_submissions',
        ),
    ]
