# Generated by Django 5.2.17 on 2026-09-11 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0003_short_table_names'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='max_attempts',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
