# Generated by Django 5.2.17 on 2026-09-19 08:38

from django.db import migrations


def remove_retired_permissions(apps, schema_editor):
    apps.get_model("auth", "Permission").objects.using(schema_editor.connection.alias).filter(content_type__app_label="assignments").delete()


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0004_assignment_max_attempts'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.RunPython(remove_retired_permissions, migrations.RunPython.noop),
        migrations.AlterModelOptions(
            name='assignment',
            options={'default_permissions': (), 'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='assignmentsubmission',
            options={'default_permissions': (), 'ordering': ['-submitted_at']},
        ),
    ]
