# Generated by Django 5.2.17 on 2026-09-13 08:38

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kind', models.CharField(max_length=30)),
                ('target', models.CharField(max_length=100)),
                ('dedupe_key', models.CharField(max_length=64, unique=True)),
                ('payload', models.JSONField(default=dict)),
                ('status', models.CharField(db_index=True, default='pending', max_length=16)),
                ('available_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('lease_token', models.UUIDField(null=True)),
                ('lease_until', models.DateTimeField(null=True)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('max_attempts', models.PositiveIntegerField(default=3)),
                ('error', models.TextField(blank=True)),
                ('result', models.JSONField(default=dict)),
                ('finished_at', models.DateTimeField(null=True)),
            ],
            options={
                'ordering': ['available_at', 'created_at', 'id'],
                'indexes': [models.Index(fields=['status', 'available_at'], name='jobs_claimable')],
            },
        ),
    ]
