# Generated by Django 5.2.17 on 2026-09-02 10:44

import django.db.models.deletion
import documents.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(blank=True, max_length=300)),
                ('original_name', models.CharField(max_length=300)),
                ('file', models.FileField(upload_to=documents.models.document_upload_path)),
                ('file_type', models.CharField(max_length=10)),
                ('file_size', models.PositiveBigIntegerField(default=0)),
                ('status', models.CharField(choices=[('uploaded', 'Uploaded'), ('processing', 'Processing'), ('under_review', 'Under review'), ('ready', 'Ready to publish'), ('published', 'Published'), ('unpublished', 'Unpublished'), ('archived', 'Archived'), ('error', 'Error')], db_index=True, default='uploaded', max_length=30)),
                ('processed_markdown_path', models.CharField(blank=True, max_length=500)),
                ('extracted_headings', models.JSONField(blank=True, default=list)),
                ('outline_source', models.CharField(blank=True, max_length=30)),
                ('parse_mode', models.CharField(blank=True, max_length=30)),
                ('error_message', models.TextField(blank=True)),
                ('processing_started_at', models.DateTimeField(blank=True, null=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('unpublished_at', models.DateTimeField(blank=True, null=True)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('content_version', models.PositiveIntegerField(default=1)),
                ('last_edited_at', models.DateTimeField(blank=True, null=True)),
                ('last_edited_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('published_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documents', to='academics.subject')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['subject', 'status'], name='documents_d_subject_9a7f14_idx')],
            },
        ),
    ]
