# Generated by Django 6.1.1 on 2026-09-03 12:45

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
        ('learning', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentChunk',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('content_version', models.PositiveIntegerField(db_index=True)),
                ('order', models.PositiveIntegerField()),
                ('text', models.TextField()),
                ('char_count', models.PositiveIntegerField(default=0)),
                ('page_start', models.PositiveIntegerField(blank=True, null=True)),
                ('page_end', models.PositiveIntegerField(blank=True, null=True)),
                ('heading', models.CharField(blank=True, max_length=300)),
                ('terms', models.JSONField(blank=True, default=dict)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='documents.document')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='learning.module')),
            ],
            options={
                'ordering': ['module', 'order'],
                'indexes': [models.Index(fields=['module', 'content_version'], name='documents_d_module__f0d97f_idx')],
                'constraints': [models.UniqueConstraint(fields=('module', 'content_version', 'order'), name='uniq_chunk_per_module_version')],
            },
        ),
    ]
