# Generated by Django 5.2.17 on 2026-09-04 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_document_chunk'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DocumentChunk',
        ),
    ]
