# Generated by Django 5.2.17 on 2026-09-10 21:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0006_document_content_hash'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='document',
            new_name='books_subject_1a1ffb_idx',
            old_name='documents_d_subject_9a7f14_idx',
        ),
        migrations.AlterModelTable(
            name='document',
            table='books',
        ),
        migrations.AlterModelTable(
            name='documentchunk',
            table='module_text_chunks',
        ),
    ]
