# Generated by Django 5.2.17 on 2026-09-15 14:34

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0003_short_table_names'),
        ('documents', '0009_localauthoringreceipt'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LocalBookUpload',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('operation_id', models.UUIDField()),
                ('original_name', models.CharField(max_length=300)),
                ('sha256', models.CharField(max_length=64)),
                ('size', models.PositiveBigIntegerField()),
                ('received', models.PositiveBigIntegerField(default=0)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='academics.subject')),
            ],
        ),
        migrations.CreateModel(
            name='LocalBookUploadChunk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offset', models.PositiveBigIntegerField()),
                ('data', models.BinaryField()),
                ('upload', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='documents.localbookupload')),
            ],
        ),
        migrations.AddConstraint(
            model_name='localbookupload',
            constraint=models.UniqueConstraint(fields=('actor', 'operation_id'), name='unique_local_book_upload'),
        ),
        migrations.AddConstraint(
            model_name='localbookuploadchunk',
            constraint=models.UniqueConstraint(fields=('upload', 'offset'), name='unique_local_book_chunk'),
        ),
    ]
