# Generated by Django 5.2.17 on 2026-09-17 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0010_localbookupload_localbookuploadchunk_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='outline_quality',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
