# Generated by Django 5.2.17 on 2026-09-17 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0011_document_outline_quality'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='title_is_custom',
            field=models.BooleanField(default=False),
        ),
    ]
