# Generated by Django 5.2.17 on 2026-09-13 08:38

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('documents', '0008_document_outline_strategy'),
        ('learning', '0003_short_table_names'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthoringState',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source_digest', models.CharField(blank=True, max_length=64)),
                ('policy', models.JSONField(default=dict)),
                ('policy_proposal', models.JSONField(blank=True, default=dict)),
                ('document', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='study_authoring', to='documents.document')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ContentBlock',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('position', models.PositiveIntegerField()),
                ('current_revision', models.PositiveIntegerField(default=1)),
                ('active', models.BooleanField(default=True)),
                ('origin', models.CharField(default='imported', max_length=16)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='study_blocks', to='learning.module')),
            ],
            options={
                'ordering': ['module_id', 'position', 'id'],
            },
        ),
        migrations.CreateModel(
            name='StudyPackage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version', models.PositiveIntegerField()),
                ('digest', models.CharField(max_length=64)),
                ('envelope', models.TextField()),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='study_packages', to='documents.document')),
                ('published_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-version'],
            },
        ),
        migrations.CreateModel(
            name='Observation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('block_id', models.UUIDField()),
                ('block_revision', models.PositiveIntegerField()),
                ('question_id', models.UUIDField(null=True)),
                ('state', models.CharField(max_length=30)),
                ('move', models.CharField(max_length=30)),
                ('outcome', models.CharField(max_length=30)),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='observations', to='study.studypackage')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='StudyQuestion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('body', models.JSONField()),
                ('references', models.JSONField()),
                ('generator', models.CharField(default='manual', max_length=30)),
                ('model_name', models.CharField(blank=True, max_length=300)),
                ('review', models.JSONField(default=dict)),
                ('approved_digest', models.CharField(blank=True, max_length=64)),
                ('approved_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='study_questions', to='documents.document')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TeachingAid',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('block_revision', models.PositiveIntegerField()),
                ('simpler_text', models.TextField(blank=True)),
                ('example_ids', models.JSONField(default=list)),
                ('diagnostic_ids', models.JSONField(default=list)),
                ('prerequisite_ids', models.JSONField(default=list)),
                ('block', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='teaching_aid', to='study.contentblock')),
                ('reviewed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BlockRevision',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('revision', models.PositiveIntegerField()),
                ('kind', models.CharField(choices=[('prose', 'prose'), ('table', 'table'), ('figure', 'figure'), ('worked_example', 'worked_example'), ('callout', 'callout')], max_length=20)),
                ('title', models.CharField(max_length=300)),
                ('text', models.TextField()),
                ('data', models.JSONField(default=dict)),
                ('digest', models.CharField(max_length=64)),
                ('block', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='revisions', to='study.contentblock')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('block', 'revision'), name='study_unique_block_revision')],
            },
        ),
        migrations.CreateModel(
            name='StudyAsset',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('digest', models.CharField(max_length=64)),
                ('file', models.FileField(upload_to='study-assets/')),
                ('source_location', models.CharField(blank=True, max_length=300)),
                ('caption', models.CharField(blank=True, max_length=500)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='study_assets', to='documents.document')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('document', 'digest'), name='study_unique_asset')],
            },
        ),
        migrations.AddConstraint(
            model_name='studypackage',
            constraint=models.UniqueConstraint(fields=('document', 'version'), name='study_unique_package_version'),
        ),
    ]
