# Generated by Django 5.2.17 on 2026-09-10 21:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='auditlog',
            new_name='audit_log_target__0238a6_idx',
            old_name='audit_audit_target__2d648a_idx',
        ),
        migrations.AlterModelTable(
            name='auditlog',
            table='audit_log',
        ),
    ]
